//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroondasDigital.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MicroondasDigital.Domain.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\deff0{\fonttbl{\f0 \fswiss Helvetica;}{\f1 Courier;}}
        ///{\colortbl;\red255\green0\blue0;\red0\green0\blue255;}
        ///\widowctrl\hyphauto
        ///
        ///{\pard \ql \f0 \sa180 \li0 \fi0 \b \fs32 Arroz\par}
        ///{\pard \qc \f0 \sa180 \li0 \fi0 \emdash\emdash\emdash\emdash\emdash\par}
        ///{\pard \ql \f0 \sa180 \li0 \fi0 \b \fs28 1\u186? passo\par}
        ///{\pard \ql \f0 \sa180 \li0 \fi0 Coloque o arroz no micro-ondas com os seguintes ingredientes: \par}
        ///{\pard \ql \f0 \sa180 \li360 \fi-360 \bullet \tx360\tab \u211?Ieo\par}
        ///{\par [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ArrozRtf {
            get {
                return ResourceManager.GetString("ArrozRtf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\deff0{\fonttbl{\f0 \fswiss Helvetica;}{\f1 Courier;}}
        ///{\colortbl;\red255\green0\blue0;\red0\green0\blue255;}
        ///\widowctrl\hyphauto
        ///
        ///{\pard \ql \f0 \sa180 \li0 \fi0 \b \fs32 Carne\par}
        ///{\pard \qc \f0 \sa180 \li0 \fi0 \emdash\emdash\emdash\emdash\emdash\par}
        ///{\pard \ql \f0 \sa180 \li0 \fi0 \b \fs28 1\u186? passo\par}
        ///{\pard \ql \f0 \sa180 \li0 \fi0 Coloque a carne no micro-ondas com seguintes ingredientes:\par}
        ///{\pard \ql \f0 \sa180 \li360 \fi-360 \bullet \tx360\tab 1 kg de carne\par}
        ///{\par [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CarneRtf {
            get {
                return ResourceManager.GetString("CarneRtf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\deff0{\fonttbl{\f0 \fswiss Helvetica;}{\f1 Courier;}}
        ///{\colortbl;\red255\green0\blue0;\red0\green0\blue255;}
        ///\widowctrl\hyphauto
        ///
        ///{\pard \ql \f0 \sa180 \li0 \fi0 \b \fs32 Coxinha\par}
        ///{\pard \qc \f0 \sa180 \li0 \fi0 \emdash\emdash\emdash\emdash\emdash\par}
        ///{\pard \ql \f0 \sa180 \li0 \fi0 \b \fs28 1\u186? passo\par}
        ///{\pard \ql \f0 \sa180 \li0 \fi0 Coloque a coxinha no micro-ondas.\par}
        ///{\pard \ql \f0 \sa180 \li0 \fi0 \b \fs28 2\u186? passo\par}
        ///{\pard \ql \f0 \sa180 \li0 \fi0 Informe se  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CoxinhaRtf {
            get {
                return ResourceManager.GetString("CoxinhaRtf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\deff0{\fonttbl{\f0 \fswiss Helvetica;}{\f1 Courier;}}
        ///{\colortbl;\red255\green0\blue0;\red0\green0\blue255;}
        ///\widowctrl\hyphauto
        ///
        ///{\pard \ql \f0 \sa180 \li0 \fi0 \b \fs32 Frango\par}
        ///{\pard \qc \f0 \sa180 \li0 \fi0 \emdash\emdash\emdash\emdash\emdash\par}
        ///{\pard \ql \f0 \sa180 \li0 \fi0 \b \fs28 1\u186? passo\par}
        ///{\pard \ql \f0 \sa180 \li0 \fi0 Coloque o frango no micro-ondas com os seguintes ingredientes:\par}
        ///{\pard \ql \f0 \sa180 \li360 \fi-360 \bullet \tx360\tab 1 kg de coxa e sobre [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FrangoRtf {
            get {
                return ResourceManager.GetString("FrangoRtf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\deff0{\fonttbl{\f0 \fswiss Helvetica;}{\f1 Courier;}}
        ///{\colortbl;\red255\green0\blue0;\red0\green0\blue255;}
        ///\widowctrl\hyphauto
        ///
        ///{\pard \ql \f0 \sa180 \li0 \fi0 \b \fs32 Carne\par}
        ///{\pard \qc \f0 \sa180 \li0 \fi0 \emdash\emdash\emdash\emdash\emdash\par}
        ///{\pard \ql \f0 \sa180 \li0 \fi0 \b \fs28 1\u186? passo\par}
        ///{\pard \ql \f0 \sa180 \li0 \fi0 Coloque o copo de leite no micro-ondas.\par}
        ///{\pard \ql \f0 \sa180 \li0 \fi0 \b \fs28 2\u186? passo\par}
        ///{\pard \ql \f0 \sa180 \li0 \fi0 Informe [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LeiteRtf {
            get {
                return ResourceManager.GetString("LeiteRtf", resourceCulture);
            }
        }
    }
}
